### ISSUE TITLE
wrong version encoded in v1 ASPAs

### ISSUE THREAD

**Issue by job** [APNIC-net/rpki-aspa-demo#1]
While testing for interopability, it seems the wrong version is encoded in these new objects

```
$ rpki-client -f ./t/objects/AS1000.asa
File:                     ./t/objects/AS1000.asa
Hash identifier:          2xsaUPJ/RDYSjZFiTqwUnvmICbUzflj97lSkJP/9unY=
rpki-client: ./t/objects/AS1000.asa: unexpected version 0
Validation:               N/A
```

I suspect you'll want to set this line to 1: https://github.com/APNIC-net/rpki-aspa-demo/blob/8dc918f479874222138f350350a73d8ad9029a49/bin/sign-aspa#L59

**Comment by tomhrr** [comment]
Thanks, this has been fixed now.
